ALPHA_VANTAGE_API_KEY=O68YX19Y3IVE7D7D
XAI_API_KEY=xai-y4fik5ciUttc6GoUhKmSwA4MrmVZHfVuual0aoEk18lsIRED3YiGZ0WEG1sSdBxGCweuZpho3A5xhazd
TELEGRAM_TOKEN=8403105588:AAEprjgyCxyenUnDVDv4y0gIpjupSOnPOyg
TELEGRAM_CHAT_ID=849640713
